// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmukruwvwznhcajzsxnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdWtydXd2d3puaGNhanpzeG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTkxNjYsImV4cCI6MjA3NTMzNTE2Nn0.WFpvfSdy_y61M8F6D7aso1MTgs135sxyUH-f70DODIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});